### PR TITLE
added documentation for the dust models d7 and d8

### PR DESCRIPTION
**Pull request by zonca**
@brandonshensley can you please double-check the description of the HD2017 models?

### CODE REVIEW

**Comment by brandonshensley** [comment]
> @brandonshensley can you please double-check the description of the HD2017 models?

Could you point me to where the relevant d7 and d8 model parameters are initialized? E.g., where if f_fe being set for d7? Thanks!

**Comment by zonca** [comment]
See presets.cfg, it is also linked inside the file in this pull request

**Comment by brandonshensley** [comment]
Yes, the descriptions are consistent with the parameter values in presets.cfg. Thanks!

**Comment by zonca** [comment]
thanks!
Travis build fails just for `astropy-dev`, merging

**Pull request merged**
