### PR TITLE
Add extragalactic

### PR DESCRIPTION
**Pull request by bthorne93**
Added `extragalactic` submodule and `InterpolatedCIB` model.

### CODE REVIEW

**Comment by zonca** [comment]
@bthorne93 instead of this, what about using https://github.com/zonca/pysm_interpolating_component?

**Comment by zonca** [comment]
I can adapt that code to the new PySM and then integrate it directly inside PySM

**Comment by bthorne93** [comment]
@zonca great - please do replace!

**Comment by zonca** [comment]
ok, thanks

**Pull request closed without merging**
