### PR TITLE
changed bandpass_unit_conversion and add unit test

### PR DESCRIPTION
**Pull request by NicolettaK**
This PR implements the modifications described in https://github.com/healpy/pysm/issues/59 to `pysm3.utils.bandpass_unit_conversion`. 

Unit test is added, where a bandpass integrated CMB map in K_CMB unit is compared to the template CMB map.

### CODE REVIEW

**Comment by zonca** [comment]
thank you, I'll get to this next week

**Comment by zonca** [comment]
just noticed PySM 2 has nice tests for bandpass integration, I'll also import those here, so we have better coverage: https://github.com/bthorne93/PySM_public/blob/b3e23bb8f88182bf440b731a2bab7100a255af0d/pysm/test/test_common.py

**Comment by zonca** [comment]
@NicolettaK I have also added a comparison with PySM 2, the integration of the Planck bandpasses agrees to 0.02%, so I think this is safe to merge.

**Comment by NicolettaK** [comment]
Great!!! thanks @zonca

**Pull request merged**
